citationcff/citation.py
=> now also using name-suffix if it exists

livetest/citation_test.py, test/citation_test.py
seems better to have it as a unit test
=> moved override test to unit test

cff_converter_python/citation.py, fixtures/bibtex-6-no-date, fixtures/bibtex-6-no-doi, fixtures/bibtex-6-no-version, fixtures/citationcff-6, fixtures/codemeta-6-no-date, fixtures/codemeta-6-no-doi, fixtures/codemeta-6-no-version, fixtures/endnote-6-no-date, fixtures/endnote-6-no-doi, fixtures/endnote-6-no-version, fixtures/ris-6-no-date, fixtures/ris-6-no-doi, fixtures/ris-6-no-version, test/citation_test.py
- added functionality to remove suspect keys such as doi/version/commit/date-released; 
- added unit tests
- added fixtures
=> added functionality to remove suspect keys

cffconvert/citation.py, fixtures/7/CITATION.cff
=> now using tempdir with absolute address to avoid writing files locally

cffconvert/citation.py
=> possible fix for issue #94

CHANGELOG.rst, CITATION.cff, cffconvert/version.py, test/cli_test.py
prepared files for next release
=> prep release 1.2.0

CHANGELOG.rst, CITATION.cff, README.rst, cffconvert/version.py, requirements.txt, test/cli_test.py
- fixed a possible error with dependendy of ruamel.yaml
- updated documentation to hopefully avoid this error in the future
- updated version numbers
=> prep-1.3.2

cffconvert/gcloud.py
=> may solve silent pass of invalid CFF on Google Cloud Function

.github/workflows/testing.yml
on matrix of python 3.6, 3.7, 3.8, 3.9 and linux, windows, mac
=> added workflow to run unit tests for schema versions 1.0.3, 1.1.0, 1.2.0

cffconvert/behavior_1_0_x/apalike/apalike.py, cffconvert/behavior_1_0_x/bibtex/bibtex.py, cffconvert/behavior_1_0_x/endnote/endnote.py, cffconvert/behavior_1_0_x/ris/ris.py, cffconvert/behavior_1_0_x/schemaorg/schemaorg.py, cffconvert/behavior_1_0_x/zenodo/zenodo.py, cffconvert/behavior_1_1_x/apalike/apalike.py, cffconvert/behavior_1_1_x/bibtex/bibtex.py, cffconvert/behavior_1_1_x/endnote/endnote.py, cffconvert/behavior_1_1_x/ris/ris.py, cffconvert/behavior_1_1_x/schemaorg/schemaorg.py, cffconvert/behavior_1_1_x/zenodo/zenodo.py, cffconvert/behavior_1_2_x/apalike/apalike.py, cffconvert/behavior_1_2_x/bibtex/bibtex.py, cffconvert/behavior_1_2_x/endnote/endnote.py, cffconvert/behavior_1_2_x/ris/ris.py, cffconvert/behavior_1_2_x/schemaorg/schemaorg.py, cffconvert/behavior_1_2_x/zenodo/zenodo.py, cffconvert/behavior_shared/apalike/apalike.py, cffconvert/behavior_shared/bibtex/bibtex.py, cffconvert/behavior_shared/endnote/endnote.py, cffconvert/behavior_shared/ris/ris.py, cffconvert/behavior_shared/schemaorg/schemaorg.py, cffconvert/behavior_shared/zenodo/zenodo.py
=> Move check_cffobj to parent class

test/1.0.3/02/ris.txt, test/1.0.3/02/test_1_0_3__02_ris_object.py, test/1.0.3/03/ris.txt, test/1.0.3/03/test_1_0_3__03_ris_object.py, test/1.0.3/04/ris.txt, test/1.0.3/04/test_1_0_3__04_ris_object.py, test/1.0.3/05/ris.txt, test/1.0.3/05/test_1_0_3__05_ris_object.py, test/1.1.0/01/test_1_1_0__01_ris_object.py, test/1.1.0/02/ris.txt, test/1.1.0/02/test_1_1_0__02_ris_object.py, test/1.1.0/03/ris.txt, test/1.1.0/03/test_1_1_0__03_ris_object.py, test/1.1.0/04/ris.txt, test/1.1.0/04/test_1_1_0__04_ris_object.py, test/1.1.0/05/ris.txt, test/1.1.0/05/test_1_1_0__05_ris_object.py, test/1.1.0/06/ris.txt, test/1.1.0/06/test_1_1_0__06_ris_object.py, test/1.1.0/07/ris.txt, test/1.1.0/07/test_1_1_0__07_ris_object.py, test/1.1.0/08/ris.txt, test/1.1.0/08/test_1_1_0__08_ris_object.py, test/1.2.0/random/01/test_1_2_0_random_01_ris_object.py, test/1.2.0/random/02/ris.txt, test/1.2.0/random/02/test_1_2_0_random_02_ris_object.py, test/1.2.0/random/03/ris.txt, test/1.2.0/random/03/test_1_2_0_random_03_ris_object.py, test/1.2.0/random/04/ris.txt, test/1.2.0/random/04/test_1_2_0_random_04_ris_object.py
=> added ris object tests everywhere

setup.cfg
=> added link to source to pypi metadata

README.md, cffconvert/cli/cli.py
added longform variants for input file and output file arguments to the cli
=> added longform variants to cli

.github/workflows/linting.yml, .github/workflows/testing.yml
, not pull request or push to any
=> workflows now trigger on pull request or push to main

cffconvert/behavior_shared/zenodo_creator_shared.py
=> corrected typo in key for zenodo object shared

sonar-project.properties
specifically, I want to exclude the tests from being analyzed
=> updated sonarcloud config after migrating to src/ based directory layout

src/cffconvert/cff_1_x_x/zenodo.py
sonarcloud rightly reported high cognitive complexity on file `src/cffconvert/cff_1_x_x/zenodo.py`, this PR tries to lower it a bit
=> tried to lower cognitive complexity

.pre-commit-config.yaml, .prospector.yml, README.dev.md, pyproject.toml, src/cffconvert/cff_1_0_x/citation.py, src/cffconvert/cff_1_1_x/citation.py, src/cffconvert/cff_1_2_x/citation.py, src/cffconvert/cff_1_3_x/citation.py, src/cffconvert/cff_1_x_x/ris.py, src/cffconvert/cff_1_x_x/schemaorg.py, src/cffconvert/cff_1_x_x/zenodo.py, src/cffconvert/citation.py
- replaced pylint with ruff
- added pyroma as a separate tool, not tied to prospector
- updated dev docs
- updated pre-commit config
- removed some linter comments related to pylint and pep8
=> Lint configuration

src/cffconvert/cli/cli.py
- added a tag line for the program as part of the usage text
- added call to action for starring on github as an epilog
=> Updated usage text

src/cffconvert/lib/cff_1_0_x/citation.py, src/cffconvert/lib/cff_1_1_x/citation.py, src/cffconvert/lib/cff_1_2_x/citation.py, src/cffconvert/lib/cff_1_3_x/citation.py, src/cffconvert/lib/constants.py
=> replaced repeated literal string with a constant

README.md
Updated usage text in README.md
=> Readme usage text
