cff_converter_python/citation.py
livetest/citation_test.py

The tool used to only do github urls in the format
- ``https://github.com/<org>/<repo>``
With this PR , it now does urls in the formats
- ``https://github.com/<org>/<repo>``
- ``https://github.com/<org>/<repo>/tree/<sha>``
- ``https://github.com/<org>/<repo>/tree/<tagname>``
- ``https://github.com/<org>/<repo>/tree/<branchname>``
I also added livetests for each of the cases, pointing to the CFF of this repo.

Multiple GitHub url formats

---

cff_converter_python/citation.py
fixtures/bibtex-5
fixtures/codemeta-5
fixtures/endnote-5
fixtures/ris-5
livetest/citation_test.py

``doi`` and ``date-released`` from the citationcff are almost always out of date, this PR adds functionality to override those keys with custom values, for example those returned by a DOI supplier like Zenodo.
see also: https://github.com/research-software-directory/landing-page/issues/77

now able to override suspect keys like doi and date-released

---

cffconvert/citation.py
requirements.txt
test/consistency_test.py

because one of cffconvert's dependencies (``pykwalifire``) uses ``ruamel.yaml>=0.11.0,<0.12.0``:
https://github.com/sdruskat/pykwalifire/blob/d72869cab73441cb074100bd31a6c0795e16c41e/setup.py#L28
related: https://github.com/citation-file-format/cff-converter-python/issues/9

removed PyYAML dependency in favor of ruamel.yaml

---

.zenodo.json
CITATION.cff
README.rst
cffconvert/citation.py
cffconvert/cli.py
cffconvert/gcloud.py
fixtures/1/schema-dot-org.json
fixtures/2/schema-dot-org.json
fixtures/3/schema-dot-org.json
fixtures/5/schema-dot-org.json
fixtures/6/schema-dot-org-no-date.json
fixtures/6/schema-dot-org-no-doi.json
fixtures/6/schema-dot-org-no-suspect-keys.json
fixtures/6/schema-dot-org-no-version.json
test/citation_test.py
test/cli_test.py

It seems that Google was having some issues with interpreting the codemeta we generate for the Research Software Directory
- https://github.com/research-software-directory/research-software-directory/blob/b2c08d59cf143f843eb5e4facd136818a9346a2a/harvesting/releases.py#L176
- https://github.com/research-software-directory/research-software-directory/blob/b2c08d59cf143f843eb5e4facd136818a9346a2a/harvesting/releases.py#L223
, therefore I added an export that just uses schema.org for its context, instead of both codemeta and schema.org.

Schema.org

---

cffconvert/citation.py

This fix hard-codes the use of schema version 1.0.3-1 for CFF files with a value of `cff-version: 1.0.3`.
This hard-coding seems reasonable as 1.0.3-1 is the last version that will use the `schema.yaml` + *pykwalifire* validation method.
This PR fixes #106.

Fix #106: Use fixed schema for CFF 1.0.3

---

CHANGELOG.rst
CITATION.cff
cffconvert/citation.py
cffconvert/version.py
test/cli_test.py

except for the date in CITATION.cff, basically ready for release 1.1.0 (of https://github.com/citation-file-format/citation-file-format).
fixes #119
refs https://github.com/citation-file-format/citation-file-format/issues/75

Schema retrieval

---

MANIFEST.in
cffconvert/citation.py
cffconvert/schemas/1.0.1/schema.yaml
cffconvert/schemas/1.0.2/schema.yaml
cffconvert/schemas/1.0.3/schema.yaml
cffconvert/schemas/1.1.0/schema.yaml
cffconvert/schemas/1.2.0/schema.json
setup.cfg

for `1.0.1`, `1.0.2`, `1.0.3`, `1.1.0`, and `1.2.0` in a new directory schemas/ using the links here:
https://github.com/citation-file-format/cff-converter-python/blob/0aaefbaf339e3b39fee43138355aaef24a9af8e3/cffconvert/citation.py#L130-L135
and
https://zenodo.org/record/5171937/files/schema.json
refs #169

added schemas 

---

.zenodo.json
README.dev.md
setup.cfg
test/1.0.3/01/test_1_0_3__01_cli.py
test/test_consistent_versioning.py

Instead of bumpversion, I'm now using a unit test that tests for consistency with `cffconvert/version::__version__`
Refs: #211, #188

version string consistency checks

---

.pre-commit-hooks.yaml

Closes #268 
This seems to work fine. The issue is that if the validation doesn't pass, some errors cause the whole schema to be printed, which takes a lot of lines, so you have to scroll far up to find the actual helpful message.

Provide pre-commit hook

---

.prospector.yml

- `pep8` changed its name to `pycodestyle`
- `pep257` changed its name to `pydocstyle`
, configuration for prospector needed to be updated to avoid linting errors

updated the config for prospector, after some tools were renamed

---

setup.cfg

I tested with `jsonschema` 4.6.0 and found that all the tests in `test/` and `livetest/` still pass.

Allow jsonschema 4.x

---

.github/workflows/linting.yml
.github/workflows/testing.yml

This PR updates the CI configuration to remove unsupported and add new Python versions.
One issue remains, even with this update: #296, which is a bug in prospector.

Update CI configuration

---

cffconvert/behavior_1_0_x/citation.py
cffconvert/behavior_1_1_x/citation.py
cffconvert/behavior_1_2_x/citation.py
cffconvert/cli/cli.py
cffconvert/cli/validate_or_write_output.py

Made a quick pull request for controlling the output of the validation errors (#278) when validating a `CITATION.cff` file through the command-line i.e., `cffconvert --validate`. 
Testing this should be easy enough but the `./test` folder is quite expansive and did not find a simple place to put tests for this functionality. Hopefully this is helpful! Just wanted to quickly implement a draft of the simple fix for the issue.
Something like this should be in my opinion implemented before letting people use the `pre-commit` hook implemented on the default branch (#284).
Let me know about things to change/fix/add!

Enabled verbosity control from cli

---

src/cffconvert/cli/validate_or_write_output.py

refs:
- #266
In this PR:
- added exit code 1 when failing validation prior to converting

exit code 1 when failing validation on convert

---

src/cffconvert/cff_1_2_x/citation.py

Following a prospector recommendation broke the truncated output for validation errors for CITATION.cff files with `cff-version: 1.2.0`. This PR fixes that again by reverting to the pre-propsector code, and adding a local pylint exception

Error message truncated again

---

tests/cff_1_0_3/c/.zenodo.json
tests/cff_1_0_3/c/CITATION.cff
tests/cff_1_0_3/c/codemeta.json
tests/cff_1_0_3/c/schemaorg.json
tests/cff_1_0_3/c/test_citation.py
tests/cff_1_0_3/c/test_codemeta_object.py
tests/cff_1_0_3/c/test_schemaorg_object.py
tests/cff_1_0_3/c/test_zenodo_object.py

Refs:
- #297
This PR updates a CITATION.cff file that was used in testing but didnt pass validation because of an issue with one of the authors' orcid ending in `X` (which is legal but the 1.0.3 schema didnt recognize that). Fixed by removing the orcid key altogether and using the other author's orcid instead.
```shell
find ./tests -type f -name CITATION.cff -exec cffconvert -i {} --validate \; 
```
show all passing now whereas `main` had an error for `tests/cff_1_0_3/c/CITATION.cff`

updated previously invalid cff file used in testing

---

.zenodo.json
CHANGELOG.md
CITATION.cff
Dockerfile
README.dev.md
docs/alternative-install-options.md
pyproject.toml
src/cffconvert/version.py
tests/cff_1_0_3/a/test_cli.py
tests/cff_1_1_0/a/test_cli.py
tests/cff_1_2_0/identifiers/D_/test_cli.py
tests/cff_1_3_0/identifiers/sources/D_/test_cli.py

- bumped cffconvert version to 3.0.0a0
- `.zenodo.json`, `CITATION.cff`: split the authors into author and contributors; exported the identifiers, both using preliminary functionality based on preliminary schema
- updated alpine image version in Dockerfile
- updated other instances of version number

bumped cffconvert version to 3.0.0a0

---

src/cffconvert/cff_1_0_x/citation.py
src/cffconvert/cff_1_1_x/citation.py
src/cffconvert/cff_1_2_x/citation.py
src/cffconvert/cff_1_3_x/citation.py

This PR changes the way yaml text is parsed. It appears that ruamel.yaml persists some of its configuration, see
- #343
This PR stores the timestamp parser that is present before we change anything, and restores it afterwards. Additionally it configures the parser to read timestamps as timestamp under cff-version 1.0.x and 1.1.x and as string under cff-version 1.2.x and 1.3.x, but now using ruamel.yaml's own constructor methods from `YAML.SafeConstructor`, as opposed to whatever it finds was previously configured as a parser.

testing order bug

---

src/cffconvert/cli/constants.py
src/cffconvert/cli/rawify_url.py
src/cffconvert/cli/read_from_url.py

Refs:
- #263
- #353
Updated making calls to github api 
- to retrieve the default branch (#263)
- to request with mime type
- to have the option of making the call authenticated (#353)

Updated how GitHub api calls are made

---

.pre-commit-config.yaml
README.md
docs/alternative-install-options.md

- added precommit task to check for broken links in markdown
- updated the errors it found
- left one expected error:
```
ERROR: 1 dead links found in README.dev.md !
[✖] https://github.com/citation-file-format/cffconvert/blob/3.0.0a0/cffconvert/behavior_shared/schemaorg_author_shared.py → Status: 404
```

Link checker pre commit

---

.github/dependabot.yml

Hi! I noticed that CI is throwing deprecation warnings due to out-of-date action versions (like `actions/checkout@v2` -- [recent example](https://github.com/citation-file-format/cffconvert/actions/runs/6720385692)).
Rather than submitting a PR to update the versions once, this PR introduces a Dependabot configuration that will submit a PR to update action versions (if needed) once each month.
If this merges, Dependabot will immediately submit a PR to address the out-of-date versions and will continue to keep the actions up-to-date in perpetuity.

Add Dependabot config to autoupdate GitHub action versions

---

docs/alternative-install-options.md

This pull request proposes a minor update of alternative install options document. Since **cffconvert** package is also available in various Linux distributions and some users prefer installing packages using distro-specific package managers, I recommend adding another section to this document. I am the maintainer of this package for Alpine Linux and Fedora.

Update alternative install options
